name: Rust CI & Publish

on:
  push:
    # branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy linter
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests for all packages
        run: cargo test --all

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: test_and_lint
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish `oxmpl` core crate
        run: cargo publish --package oxmpl --token ${{ secrets.CARGO_TOKEN }}

      - name: Wait for `oxmpl` to be indexed
        run: sleep 60

      - name: Update dependency and publish `oxmpl-py` bindings crate
        run: |
          TAG_NAME="${{ github.ref_name }}"
          VERSION="${TAG_NAME#v}"
          echo "Preparing to publish oxmpl-py version ${VERSION}"

          sed -i "s|oxmpl = { path = \"../oxmpl\" }|oxmpl = \"$VERSION\"|" oxmpl-py/Cargo.toml

          echo "Updated oxmpl-py/Cargo.toml:"
          cat oxmpl-py/Cargo.toml

          cargo publish --package oxmpl-py --token ${{ secrets.CARGO_TOKEN }} --allow-dirty

      - name: Update dependency and publish `oxmpl-js` bindings crate
        run: |
          TAG_NAME="${{ github.ref_name }}"
          VERSION="${TAG_NAME#v}"
          echo "Preparing to publish oxmpl-js version ${VERSION}"

          sed -i "s|oxmpl = { path = \"../oxmpl\" }|oxmpl = \"$VERSION\"|" oxmpl-js/Cargo.toml

          echo "Updated oxmpl-js/Cargo.toml:"
          cat oxmpl-js/Cargo.toml

          cargo publish --package oxmpl-js --token ${{ secrets.CARGO_TOKEN }} --allow-dirty
